-- 테이블, 시퀀스 삭제
DROP TABLE COMMENTS;
DROP TABLE REVIEWS;
DROP TABLE BOOKMARKS;
DROP TABLE ORDERDETAIL;
DROP TABLE ORDERS;
DROP TABLE CART;
DROP TABLE ONLINESALEMENU;
DROP TABLE ONLINESALECAFE;
DROP TABLE MENUFILE;
DROP TABLE CAFEFILE;
DROP TABLE MENU;
DROP TABLE CATEGORYS;
DROP TABLE CAFETAGS;
DROP TABLE TAGS;
DROP TABLE CAFE;
DROP TABLE MEMBERS;

DROP SEQUENCE CAFE_CAFE_NO_SEQ;
DROP SEQUENCE TAGS_TAG_NO_SEQ;
DROP SEQUENCE CATEGORYS_CATEGOGY_NO_SEQ;
DROP SEQUENCE MENU_MENU_NO_SEQ;
DROP SEQUENCE CAFEFILE_CFILE_NO_SEQ;
DROP SEQUENCE MENUFILE_MFILE_NO_SEQ;
DROP SEQUENCE ORDERS_ORDER_NO_SEQ;
DROP SEQUENCE REVIEWS_REVIEW_NO_SEQ;
DROP SEQUENCE COMMENTS_COMMENT_NO_SEQ;

-- 테이블 생성
CREATE TABLE MEMBERS(
    MEMBER_ID       VARCHAR2(30),
    MEMBER_PW       VARCHAR2(16),
    MEMBER_NAME     VARCHAR2(10),
    MEMBER_BIRTH    DATE,
    MEMBER_NICKNAME VARCHAR2(30),
    MEMBER_ADDRESS1 VARCHAR2(60),
    MEMBER_ADDRESS2 VARCHAR2(60),
    MEMBER_TEL      VARCHAR2(13)
);
ALTER TABLE MEMBERS ADD CONSTRAINT MEMBERS_PK PRIMARY KEY(MEMBER_ID);
ALTER TABLE MEMBERS ADD UNIQUE(MEMBER_TEL);
ALTER TABLE MEMBERS MODIFY (MEMBER_PW NOT NULL);
ALTER TABLE MEMBERS MODIFY (MEMBER_NAME NOT NULL);
ALTER TABLE MEMBERS MODIFY (MEMBER_BIRTH NOT NULL);
ALTER TABLE MEMBERS MODIFY (MEMBER_NICKNAME NOT NULL);
ALTER TABLE MEMBERS MODIFY (MEMBER_ADDRESS1 NOT NULL);
ALTER TABLE MEMBERS MODIFY (MEMBER_ADDRESS2 NOT NULL);
ALTER TABLE MEMBERS MODIFY (MEMBER_TEL NOT NULL);

CREATE TABLE CAFE(
    CAFE_NO         NUMBER(10),
    CAFE_OWNERID    VARCHAR2(30),
    CAFE_NAME       VARCHAR2(60),
    BN              VARCHAR2(12),
    CAFE_ADDRESS1   VARCHAR2(60),
    CAFE_ADDRESS2   VARCHAR2(60),
    CAFE_TEL        VARCHAR2(13),
    OPEN_TIME       VARCHAR2(7),
    CLOSE_TIME      VARCHAR2(7),
    CAFE_CONTENT    CLOB
);
ALTER TABLE CAFE ADD CONSTRAINT CAFE_PK PRIMARY KEY(CAFE_NO);
ALTER TABLE CAFE ADD CONSTRAINT CAFE_FK1 FOREIGN KEY(CAFE_OWNERID) REFERENCES MEMBERS(MEMBER_ID) ON DELETE CASCADE;
ALTER TABLE CAFE ADD UNIQUE(CAFE_OWNERID);
ALTER TABLE CAFE ADD UNIQUE(BN);
ALTER TABLE CAFE MODIFY (CAFE_OWNERID NOT NULL);
ALTER TABLE CAFE MODIFY (CAFE_NAME NOT NULL);
ALTER TABLE CAFE MODIFY (BN NOT NULL);
ALTER TABLE CAFE MODIFY (CAFE_ADDRESS1 NOT NULL);
ALTER TABLE CAFE MODIFY (CAFE_ADDRESS2 NOT NULL);
ALTER TABLE CAFE MODIFY (CAFE_TEL NOT NULL);
ALTER TABLE CAFE MODIFY (OPEN_TIME NOT NULL);
ALTER TABLE CAFE MODIFY (CLOSE_TIME NOT NULL);
ALTER TABLE CAFE MODIFY (CAFE_CONTENT NOT NULL);

CREATE TABLE BOOKMARKS(
    MEMBER_ID       VARCHAR2(30),
    CAFE_NO         NUMBER(10)
);
ALTER TABLE BOOKMARKS ADD CONSTRAINT BOOKMARKS_PK PRIMARY KEY(MEMBER_ID, CAFE_NO);
ALTER TABLE BOOKMARKS ADD CONSTRAINT BOOKMARKS_FK1 FOREIGN KEY(MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID) ON DELETE CASCADE;
ALTER TABLE BOOKMARKS ADD CONSTRAINT BOOKMARKS_FK2 FOREIGN KEY(CAFE_NO) REFERENCES CAFE(CAFE_NO) ON DELETE CASCADE;

CREATE TABLE TAGS(
    TAG_NO          NUMBER(4),
    TAG_NAME        VARCHAR2(30)
);
ALTER TABLE TAGS ADD CONSTRAINT TAGS_PK PRIMARY KEY(TAG_NO);
ALTER TABLE TAGS MODIFY (TAG_NAME NOT NULL);

CREATE TABLE CAFETAGS(
    CAFE_NO         NUMBER(10),
    TAG_NO          NUMBER(4)
);
ALTER TABLE CAFETAGS ADD CONSTRAINT CAFETAGS_PK PRIMARY KEY(CAFE_NO, TAG_NO);
ALTER TABLE CAFETAGS ADD CONSTRAINT CAFETAGS_FK1 FOREIGN KEY(CAFE_NO) REFERENCES CAFE(CAFE_NO) ON DELETE CASCADE;
ALTER TABLE CAFETAGS ADD CONSTRAINT CAFETAGS_FK2 FOREIGN KEY(TAG_NO) REFERENCES TAGS(TAG_NO) ON DELETE CASCADE;

CREATE TABLE CATEGORYS(
    CATEGOGY_NO          NUMBER(4),
    CATEGOGY_NAME        VARCHAR2(30)
);
ALTER TABLE CATEGORYS ADD CONSTRAINT CATEGORYS_PK PRIMARY KEY(CATEGOGY_NO);
ALTER TABLE CATEGORYS MODIFY (CATEGOGY_NAME NOT NULL);

CREATE TABLE MENU(
    MENU_NO         NUMBER(10),
    MENU_NAME       VARCHAR2(60),
    MENU_PRICE      NUMBER(10),
    MENU_CONTENT    VARCHAR2(150),
    MENU_CATEGORY   NUMBER(4),
    CAFE_NO         NUMBER(10)
);
ALTER TABLE MENU ADD CONSTRAINT MENU_PK PRIMARY KEY(MENU_NO);
ALTER TABLE MENU ADD CONSTRAINT MENU_FK1 FOREIGN KEY(CAFE_NO) REFERENCES CAFE(CAFE_NO) ON DELETE CASCADE;
ALTER TABLE MENU ADD CONSTRAINT MENU_FK2 FOREIGN KEY(MENU_CATEGORY) REFERENCES CATEGORYS(CATEGOGY_NO) ON DELETE CASCADE;
ALTER TABLE MENU MODIFY (MENU_NAME NOT NULL);
ALTER TABLE MENU MODIFY (MENU_PRICE NOT NULL);
ALTER TABLE MENU MODIFY (MENU_CONTENT NOT NULL);
ALTER TABLE MENU MODIFY (MENU_CATEGORY NOT NULL);
ALTER TABLE MENU MODIFY (CAFE_NO NOT NULL);

CREATE TABLE CAFEFILE(
    CFILE_NO            NUMBER(10),
    CFILE_ORIGIN_NAME   VARCHAR2(150),
    CFILE_CHANGE_NAME   VARCHAR2(150),
    CFILE_SIZE          VARCHAR2(45),
    CFILE_TYPE          VARCHAR2(100),
    CFILE_PATH          VARCHAR2(100),
    CAFE_NO             NUMBER(10)
);
ALTER TABLE CAFEFILE ADD CONSTRAINT CAFEFILE_PK PRIMARY KEY(CFILE_NO);
ALTER TABLE CAFEFILE ADD CONSTRAINT CAFEFILE_FK1 FOREIGN KEY(CAFE_NO) REFERENCES CAFE(CAFE_NO) ON DELETE CASCADE;
ALTER TABLE CAFEFILE MODIFY (CFILE_ORIGIN_NAME NOT NULL);
ALTER TABLE CAFEFILE MODIFY (CFILE_CHANGE_NAME NOT NULL);
ALTER TABLE CAFEFILE MODIFY (CFILE_SIZE NOT NULL);
ALTER TABLE CAFEFILE MODIFY (CFILE_TYPE NOT NULL);
ALTER TABLE CAFEFILE MODIFY (CFILE_PATH NOT NULL);
ALTER TABLE CAFEFILE MODIFY (CAFE_NO NOT NULL);

CREATE TABLE MENUFILE(
    MFILE_NO            NUMBER(10),
    MFILE_ORIGIN_NAME   VARCHAR2(150),
    MFILE_CHANGE_NAME   VARCHAR2(150),
    MFILE_SIZE          VARCHAR2(45),
    MFILE_TYPE          VARCHAR2(100),
    MFILE_PATH          VARCHAR2(100),
    MENU_NO             NUMBER(10)
);
ALTER TABLE MENUFILE ADD CONSTRAINT MENUFILE_PK PRIMARY KEY(MFILE_NO);
ALTER TABLE MENUFILE ADD CONSTRAINT MENUFILE_FK1 FOREIGN KEY(MENU_NO) REFERENCES MENU(MENU_NO) ON DELETE CASCADE;
ALTER TABLE MENUFILE MODIFY (MFILE_ORIGIN_NAME NOT NULL);
ALTER TABLE MENUFILE MODIFY (MFILE_CHANGE_NAME NOT NULL);
ALTER TABLE MENUFILE MODIFY (MFILE_SIZE NOT NULL);
ALTER TABLE MENUFILE MODIFY (MFILE_TYPE NOT NULL);
ALTER TABLE MENUFILE MODIFY (MFILE_PATH NOT NULL);
ALTER TABLE MENUFILE MODIFY (MENU_NO NOT NULL);

CREATE TABLE ONLINESALECAFE(
    CAFE_NO         NUMBER(10)
);
ALTER TABLE ONLINESALECAFE ADD CONSTRAINT ONLINESALECAFE_PK PRIMARY KEY(CAFE_NO);
ALTER TABLE ONLINESALECAFE ADD CONSTRAINT ONLINESALECAFE_FK1 FOREIGN KEY(CAFE_NO) REFERENCES CAFE(CAFE_NO) ON DELETE CASCADE;

CREATE TABLE ONLINESALEMENU(
    MENU_NO         NUMBER(10),
    MENU_CATEGORY   NUMBER(4),
    MENU_NAME       VARCHAR2(60),
    MENU_PRICE      NUMBER(10),
    MENU_CONTENT    VARCHAR2(150),
    CAFE_NO         NUMBER(10)
);
ALTER TABLE ONLINESALEMENU ADD CONSTRAINT ONLINESALEMENU_PK PRIMARY KEY(MENU_NO);
ALTER TABLE ONLINESALEMENU ADD CONSTRAINT ONLINESALEMENU_FK1 FOREIGN KEY(CAFE_NO) REFERENCES ONLINESALECAFE(CAFE_NO) ON DELETE CASCADE;
ALTER TABLE ONLINESALEMENU MODIFY (MENU_CATEGORY NOT NULL);
ALTER TABLE ONLINESALEMENU MODIFY (MENU_NAME NOT NULL);
ALTER TABLE ONLINESALEMENU MODIFY (MENU_PRICE NOT NULL);
ALTER TABLE ONLINESALEMENU MODIFY (MENU_CONTENT NOT NULL);
ALTER TABLE ONLINESALEMENU MODIFY (CAFE_NO NOT NULL);

CREATE TABLE CART(
    MEMBER_ID       VARCHAR2(30),
    CAFE_NO         NUMBER(10),
    MENU_NO         NUMBER(10),
    MENU_NAME       VARCHAR2(60),
    MENU_COUNT      NUMBER(5),
    MENU_PRICE      NUMBER(10)
);
ALTER TABLE CART ADD CONSTRAINT CART_PK PRIMARY KEY(MEMBER_ID, MENU_NO);
ALTER TABLE CART ADD CONSTRAINT CART_FK1 FOREIGN KEY(MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID) ON DELETE CASCADE;
ALTER TABLE CART ADD CONSTRAINT CART_FK2 FOREIGN KEY(CAFE_NO) REFERENCES ONLINESALECAFE(CAFE_NO) ON DELETE CASCADE;
ALTER TABLE CART ADD CONSTRAINT CART_FK3 FOREIGN KEY(MENU_NO) REFERENCES ONLINESALEMENU(MENU_NO) ON DELETE CASCADE;
ALTER TABLE CART MODIFY (CAFE_NO NOT NULL);
ALTER TABLE CART MODIFY (MENU_NAME NOT NULL);
ALTER TABLE CART MODIFY (MENU_COUNT NOT NULL);
ALTER TABLE CART MODIFY (MENU_PRICE NOT NULL);

CREATE TABLE ORDERS(
    ORDER_NO            NUMBER(10),
    MEMBER_ID           VARCHAR2(30),
    CAFE_NO             NUMBER(10),
    ORDER_PRICE         NUMBER(10),
    ORDER_DATE          TIMESTAMP,
    ORDER_ADDRESS1      VARCHAR2(60),
    ORDER_ADDRESS2      VARCHAR2(60),
    ORDER_PAYMENTTYPE   VARCHAR2(20),
    ORDER_RECEIVETYPE   VARCHAR2(10),
    ORDER_STATUS        VARCHAR2(15)
);
ALTER TABLE ORDERS ADD CONSTRAINT ORDERS_PK PRIMARY KEY(ORDER_NO);
ALTER TABLE ORDERS ADD CONSTRAINT ORDERS_FK1 FOREIGN KEY(MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID) ON DELETE CASCADE;
ALTER TABLE ORDERS ADD CONSTRAINT ORDERS_FK2 FOREIGN KEY(CAFE_NO) REFERENCES ONLINESALECAFE(CAFE_NO) ON DELETE CASCADE;
ALTER TABLE ORDERS MODIFY (MEMBER_ID NOT NULL);
ALTER TABLE ORDERS MODIFY (CAFE_NO NOT NULL);
ALTER TABLE ORDERS MODIFY (ORDER_PRICE NOT NULL);
ALTER TABLE ORDERS MODIFY (ORDER_DATE NOT NULL);
ALTER TABLE ORDERS MODIFY (ORDER_ADDRESS1 NOT NULL);
ALTER TABLE ORDERS MODIFY (ORDER_ADDRESS2 NOT NULL);
ALTER TABLE ORDERS MODIFY (ORDER_PAYMENTTYPE NOT NULL);
ALTER TABLE ORDERS MODIFY (ORDER_RECEIVETYPE NOT NULL);
ALTER TABLE ORDERS MODIFY (ORDER_STATUS NOT NULL);
ALTER TABLE ORDERS MODIFY (ORDER_DATE DEFAULT SYSTIMESTAMP);

CREATE TABLE ORDERDETAIL(
    ORDER_NO        NUMBER(10),
    MENU_NO         NUMBER(10),
    MENU_NAME       VARCHAR2(60),
    MENU_COUNT      NUMBER(5),
    MENU_PRICE      NUMBER(10)
);
ALTER TABLE ORDERDETAIL ADD CONSTRAINT ORDERDETAIL_PK PRIMARY KEY(ORDER_NO, MENU_NO);
ALTER TABLE ORDERDETAIL ADD CONSTRAINT ORDERDETAIL_FK1 FOREIGN KEY(ORDER_NO) REFERENCES ORDERS(ORDER_NO) ON DELETE CASCADE;
ALTER TABLE ORDERDETAIL ADD CONSTRAINT ORDERDETAIL_FK2 FOREIGN KEY(MENU_NO) REFERENCES ONLINESALEMENU(MENU_NO) ON DELETE CASCADE;
ALTER TABLE ORDERDETAIL MODIFY (MENU_NAME NOT NULL);
ALTER TABLE ORDERDETAIL MODIFY (MENU_COUNT NOT NULL);
ALTER TABLE ORDERDETAIL MODIFY (MENU_PRICE NOT NULL);

CREATE TABLE ADDRESSBOOK(
    ADDRESS_NO      NUMBER(10),
    MEMBER_ID       VARCHAR2(30),
    ADDRESS1        VARCHAR2(60),
    ADDRESS2        VARCHAR2(60)
);
ALTER TABLE ADDRESSBOOK ADD CONSTRAINT ADDRESSBOOK_PK PRIMARY KEY(ADDRESS_NO);
ALTER TABLE ADDRESSBOOK ADD CONSTRAINT ADDRESSBOOK_FK1 FOREIGN KEY(MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID) ON DELETE CASCADE;

CREATE TABLE REVIEWS(
    REVIEW_NO       NUMBER(10),
    REVIEW_TITLE    VARCHAR2(60),
    REVIEW_CONTENT  CLOB,
    REVIEW_DATE     TIMESTAMP,
    MEMBER_ID       VARCHAR2(30),
    CAFE_NO         NUMBER(10)
);
ALTER TABLE REVIEWS ADD CONSTRAINT REVIEWS_PK PRIMARY KEY(REVIEW_NO);
ALTER TABLE REVIEWS ADD CONSTRAINT REVIEWS_FK1 FOREIGN KEY(MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID) ON DELETE CASCADE;
ALTER TABLE REVIEWS ADD CONSTRAINT REVIEWS_FK2 FOREIGN KEY(CAFE_NO) REFERENCES CAFE(CAFE_NO) ON DELETE CASCADE;
ALTER TABLE REVIEWS MODIFY (REVIEW_TITLE NOT NULL);
ALTER TABLE REVIEWS MODIFY (REVIEW_CONTENT NOT NULL);
ALTER TABLE REVIEWS MODIFY (REVIEW_DATE NOT NULL);
ALTER TABLE REVIEWS MODIFY (MEMBER_ID NOT NULL);
ALTER TABLE REVIEWS MODIFY (CAFE_NO NOT NULL);
ALTER TABLE REVIEWS MODIFY (REVIEW_DATE DEFAULT SYSTIMESTAMP);

CREATE TABLE COMMENTS(
    COMMENT_NO      NUMBER(10),
    COMMENT_CONTENT CLOB,
    COMMENT_DATE    TIMESTAMP,
    CAFE_NO         NUMBER(10),
    REVIEW_NO       NUMBER(10)
);
ALTER TABLE COMMENTS ADD CONSTRAINT COMMENTS_PK PRIMARY KEY(COMMENT_NO);
ALTER TABLE COMMENTS ADD CONSTRAINT COMMENTS_FK1 FOREIGN KEY(CAFE_NO) REFERENCES CAFE(CAFE_NO) ON DELETE CASCADE;
ALTER TABLE COMMENTS ADD CONSTRAINT COMMENTS_FK2 FOREIGN KEY(REVIEW_NO) REFERENCES REVIEWS(REVIEW_NO) ON DELETE CASCADE;
ALTER TABLE COMMENTS MODIFY (COMMENT_CONTENT NOT NULL);
ALTER TABLE COMMENTS MODIFY (COMMENT_DATE NOT NULL);
ALTER TABLE COMMENTS MODIFY (CAFE_NO NOT NULL);
ALTER TABLE COMMENTS MODIFY (REVIEW_NO NOT NULL);
ALTER TABLE COMMENTS MODIFY (COMMENT_DATE DEFAULT SYSTIMESTAMP);

-- 시퀀스 생성
CREATE SEQUENCE CAFE_CAFE_NO_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999999
MINVALUE 1
NOCYCLE;

CREATE SEQUENCE TAGS_TAG_NO_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999999
MINVALUE 1
NOCYCLE;

CREATE SEQUENCE CATEGORYS_CATEGOGY_NO_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999999
MINVALUE 1
NOCYCLE;

CREATE SEQUENCE MENU_MENU_NO_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999999
MINVALUE 1
NOCYCLE;

CREATE SEQUENCE CAFEFILE_CFILE_NO_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999999
MINVALUE 1
NOCYCLE;

CREATE SEQUENCE MENUFILE_MFILE_NO_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999999
MINVALUE 1
NOCYCLE;

CREATE SEQUENCE ORDERS_ORDER_NO_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999999
MINVALUE 1
NOCYCLE;

CREATE SEQUENCE ADDRESSBOOK_ADDRESS_NO_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999999
MINVALUE 1
NOCYCLE;

CREATE SEQUENCE REVIEWS_REVIEW_NO_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999999
MINVALUE 1
NOCYCLE;

CREATE SEQUENCE COMMENTS_COMMENT_NO_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999999
MINVALUE 1
NOCYCLE;

-- 시퀀스번호 디폴트값으로 설정
ALTER TABLE CAFE MODIFY (CAFE_NO DEFAULT CAFE_CAFE_NO_SEQ.nextval);
ALTER TABLE TAGS MODIFY (TAG_NO DEFAULT TAGS_TAG_NO_SEQ.nextval);
ALTER TABLE CATEGORYS MODIFY (CATEGOGY_NO DEFAULT CATEGORYS_CATEGOGY_NO_SEQ.nextval);
ALTER TABLE MENU MODIFY (MENU_NO DEFAULT MENU_MENU_NO_SEQ.nextval);
-- ALTER TABLE CAFEFILE MODIFY (CFILE_NO DEFAULT CAFEFILE_CFILE_NO_SEQ.nextval);
-- ALTER TABLE MENUFILE MODIFY (MFILE_NO DEFAULT MENUFILE_MFILE_NO_SEQ.nextval);
-- ALTER TABLE ORDERS MODIFY (ORDER_NO DEFAULT ORDERS_ORDER_NO_SEQ.nextval);
ALTER TABLE ADDRESSBOOK MODIFY (ORDER_NO DEFAULT ADDRESSBOOK_ADDRESS_NO_SEQ.nextval);
ALTER TABLE REVIEWS MODIFY (REVIEW_NO DEFAULT REVIEWS_REVIEW_NO_SEQ.nextval);
ALTER TABLE COMMENTS MODIFY (COMMENT_NO DEFAULT COMMENTS_COMMENT_NO_SEQ.nextval);