DROP TABLE COMMENTS;
DROP TABLE REVIEWS;
DROP TABLE BOOKMARKS;
DROP TABLE ORDERDETAIL;
DROP TABLE ORDERS;
DROP TABLE CART;
DROP TABLE ONLINESALEMENU;
DROP TABLE ONLINESALECAFE;
DROP TABLE MENU;
DROP TABLE CATEGORYS;
DROP TABLE CAFETAGS;
DROP TABLE TAGS;
DROP TABLE CAFE;
DROP TABLE MEMBERS;

CREATE TABLE MEMBERS(
    MEMBER_ID       VARCHAR2(30),
    MEMBER_PW       VARCHAR2(16) NOT NULL,
    MEMBER_NAME     VARCHAR2(10) NOT NULL,
    MEMBER_BIRTH    DATE NOT NULL,
    MEMBER_NICKNAME VARCHAR2(30) NOT NULL,
    MEMBER_ADDRESS1 VARCHAR2(60) NOT NULL,
    MEMBER_ADDRESS2 VARCHAR2(60) NOT NULL,
    MEMBER_TEL      VARCHAR2(13) NOT NULL,
    PRIMARY KEY(MEMBER_ID),
    UNIQUE(MEMBER_TEL)
);

CREATE TABLE CAFE(
    CAFE_NO         NUMBER(10) GENERATED AS IDENTITY,
    CAFE_OWNERID    VARCHAR2(30) NOT NULL,
    CAFE_NAME       VARCHAR2(60) NOT NULL,
    BN              VARCHAR2(12) NOT NULL,
    CAFE_ADDRESS1   VARCHAR2(60) NOT NULL,
    CAFE_ADDRESS2   VARCHAR2(60) NOT NULL,
    CAFE_TEL        VARCHAR2(13) NOT NULL,
    OPEN_TIME       VARCHAR2(7) NOT NULL,
    CLOSE_TIME      VARCHAR2(7) NOT NULL,
    CAFE_CONTENT    VARCHAR2(300) NOT NULL,
    PRIMARY KEY(CAFE_NO),
    UNIQUE(CAFE_OWNERID),
    UNIQUE(BN),
    FOREIGN KEY(CAFE_OWNERID) REFERENCES MEMBERS(MEMBER_ID) ON DELETE CASCADE
);

CREATE TABLE BOOKMARKS(
    MEMBER_ID       VARCHAR2(30),
    CAFE_NO         NUMBER(10),
    PRIMARY KEY(MEMBER_ID, CAFE_NO),
    FOREIGN KEY(MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID) ON DELETE CASCADE,
    FOREIGN KEY(CAFE_NO) REFERENCES CAFE(CAFE_NO) ON DELETE CASCADE
);

CREATE TABLE TAGS(
    TAG_NO          NUMBER(10) GENERATED AS IDENTITY,
    TAG_NAME        VARCHAR2(30) NOT NULL,
    PRIMARY KEY(TAG_NO)
);

CREATE TABLE CAFETAGS(
    CAFE_NO         NUMBER(10),
    TAG_NO          NUMBER(10),
    PRIMARY KEY(CAFE_NO, TAG_NO),
    FOREIGN KEY(CAFE_NO) REFERENCES CAFE(CAFE_NO) ON DELETE CASCADE,
    FOREIGN KEY(TAG_NO) REFERENCES TAGS(TAG_NO) ON DELETE CASCADE
);

CREATE TABLE CATEGORYS(
    CATEGOGY_NO          NUMBER(10) GENERATED AS IDENTITY,
    CATEGOGY_NAME        VARCHAR2(30) NOT NULL,
    PRIMARY KEY(CATEGOGY_NO)
);

CREATE TABLE MENU(
    MENU_NO         NUMBER(10) GENERATED AS IDENTITY,
    MENU_NAME       VARCHAR2(60) NOT NULL,
    MENU_PRICE      NUMBER(10) NOT NULL,
    MENU_CONTENT    VARCHAR2(150) NOT NULL,
    MENU_CATEGORY   NUMBER(10) NOT NULL,
    CAFE_NO         NUMBER(10) NOT NULL,
    PRIMARY KEY(MENU_NO),
    FOREIGN KEY(CAFE_NO) REFERENCES CAFE(CAFE_NO) ON DELETE CASCADE,
    FOREIGN KEY(MENU_CATEGORY) REFERENCES CATEGORYS(CATEGOGY_NO) ON DELETE CASCADE
);

CREATE TABLE CAFEFILE(
    CFILE_NO        NUMBER(10) GENERATED AS IDENTITY,
    CFILE_NAME      VARCHAR2(90) NOT NULL,
    CFILE_SIZE      VARCHAR2(10) NOT NULL,
    CFILE_TYPE      VARCHAR2(10) NOT NULL,
    CFILE_PATH      VARCHAR2(100) NOT NULL,
    CAFE_NO         NUMBER(10) NOT NULL,
    PRIMARY KEY(CFILE_NO),
    FOREIGN KEY(CAFE_NO) REFERENCES CAFE(CAFE_NO) ON DELETE CASCADE
);

CREATE TABLE MENUFILE(
    MFILE_NO        NUMBER(10) GENERATED AS IDENTITY,
    MFILE_NAME      VARCHAR2(90) NOT NULL,
    MFILE_SIZE      VARCHAR2(10) NOT NULL,
    MFILE_TYPE      VARCHAR2(10) NOT NULL,
    MFILE_PATH      VARCHAR2(100) NOT NULL,
    MENU_NO         NUMBER(10) NOT NULL,
    PRIMARY KEY(MFILE_NO),
    FOREIGN KEY(MENU_NO) REFERENCES MENU(MENU_NO) ON DELETE CASCADE
);

CREATE TABLE ONLINESALECAFE(
    CAFE_NO         NUMBER(10),
    PRIMARY KEY(CAFE_NO),
    FOREIGN KEY(CAFE_NO) REFERENCES CAFE(CAFE_NO) ON DELETE CASCADE
);

CREATE TABLE ONLINESALEMENU(
    MENU_NO         NUMBER(10),
    MENU_CATEGORY   VARCHAR2(20) NOT NULL,
    MENU_NAME       VARCHAR2(60) NOT NULL,
    MENU_PRICE      NUMBER(10) NOT NULL,
    MENU_CONTENT    VARCHAR2(150) NOT NULL,
    CAFE_NO         NUMBER(10) NOT NULL,
    PRIMARY KEY(MENU_NO),
    FOREIGN KEY(CAFE_NO) REFERENCES ONLINESALECAFE(CAFE_NO) ON DELETE CASCADE
);

CREATE TABLE CART(
    MEMBER_ID       VARCHAR2(30),
    CAFE_NO         NUMBER(10) NOT NULL,
    MENU_NO         NUMBER(10) NOT NULL,
    MENU_NAME       VARCHAR2(60) NOT NULL,
    MENU_COUNT      NUMBER(10) NOT NULL,
    MENU_PRICE      NUMBER(10) NOT NULL,
    PRIMARY KEY(MEMBER_ID, MENU_NO),
    FOREIGN KEY(MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID) ON DELETE CASCADE,
    FOREIGN KEY(CAFE_NO) REFERENCES ONLINESALECAFE(CAFE_NO) ON DELETE CASCADE,
    FOREIGN KEY(MENU_NO) REFERENCES ONLINESALEMENU(MENU_NO) ON DELETE CASCADE
);

CREATE TABLE ORDERS(
    ORDER_NO        NUMBER GENERATED AS IDENTITY,
    MEMBER_ID       VARCHAR2(30) NOT NULL,
    CAFE_NO         NUMBER(10) NOT NULL,
    ORDER_PRICE     NUMBER(10) NOT NULL,
    ORDER_DATE      DATE NOT NULL,
    ORDER_ADDRESS1  VARCHAR2(60) NOT NULL,
    ORDER_ADDRESS2  VARCHAR2(60) NOT NULL,
    ORDER_STATUS    VARCHAR2(15) NOT NULL,
    PRIMARY KEY(ORDER_NO),
    FOREIGN KEY(MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID) ON DELETE CASCADE,
    FOREIGN KEY(CAFE_NO) REFERENCES ONLINESALECAFE(CAFE_NO) ON DELETE CASCADE
);

CREATE TABLE ORDERDETAIL(
    ORDER_NO        NUMBER(10),
    MENU_NO         NUMBER(10),
    MENU_NAME       VARCHAR2(60) NOT NULL,
    MENU_COUNT      NUMBER(10) NOT NULL,
    MENU_PRICE      NUMBER(10) NOT NULL,
    PRIMARY KEY(ORDER_NO, MENU_NO),
    FOREIGN KEY(ORDER_NO) REFERENCES ORDERS(ORDER_NO) ON DELETE CASCADE,
    FOREIGN KEY(MENU_NO) REFERENCES ONLINESALEMENU(MENU_NO) ON DELETE CASCADE
);

CREATE TABLE REVIEWS(
    REVIEW_NO       NUMBER(10) GENERATED AS IDENTITY,
    REVIEW_TITLE    VARCHAR2(60) NOT NULL,
    REVIEW_CONTENT  VARCHAR2(300) NOT NULL,
    REVIEW_DATE     DATE NOT NULL,
    MEMBER_ID       VARCHAR2(30) NOT NULL,
    CAFE_NO         NUMBER(10) NOT NULL,
    PRIMARY KEY(REVIEW_NO),
    FOREIGN KEY(MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID) ON DELETE CASCADE,
    FOREIGN KEY(CAFE_NO) REFERENCES CAFE(CAFE_NO) ON DELETE CASCADE
);

CREATE TABLE COMMENTS(
    COMMENT_NO      NUMBER(10) GENERATED AS IDENTITY,
    COMMENT_CONTENT VARCHAR2(300) NOT NULL,
    COMMENT_DATE    DATE NOT NULL,
    CAFE_NO         NUMBER(10) NOT NULL,
    REVIEW_NO       NUMBER(10) NOT NULL,
    PRIMARY KEY(COMMENT_NO),
    FOREIGN KEY(CAFE_NO) REFERENCES CAFE(CAFE_NO) ON DELETE CASCADE,
    FOREIGN KEY(REVIEW_NO) REFERENCES REVIEWS(REVIEW_NO) ON DELETE CASCADE
);